AllCops:
  TargetRubyVersion: 2.6
  EnabledByDefault: true

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/LineLength:
  Max: 120

Style/DocumentationMethod:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/MissingElse:
  Enabled: false
